### ISSUE TITLE
Error while uploading a file in multipart/form-data

### ISSUE THREAD

**Issue by jonathanlermitage** [dareid/chakram#102]
Here is the test code (I test a WebService that takes a file and some data, then upload it to a FTP server):

```js
let chakram = require('chakram'),
    expect = chakram.expect,
    wait = chakram.wait;
let fs = require('fs')
let path = require("path");
let g = require('./lib/globals.js'); /* I define some globals, like g.portfolioUrl: the WebService url I'll test  */
let assert = require('assert');

...

it("should put a file in root folder", function () {
        let $body = {
            action: 'putFile',
            parentPath: '/',
            filenameToStore: 'sample_picture.png'
        };
        /* "options['headers']" is already defined and a "before" step adds authentication cookie */
        options['headers']['Content-Type'] = 'multipart/form-data; charset=utf-8; boundary='
            + Math.random().toString().substr(2);
        options['formData'] = {
            pkgFile: fs.createReadStream(path.resolve(__dirname, '../test/res/sample_picture.png'))
        };
        return chakram.post(g.portfolioUrl, $body, options).then(function (response) {
            expect(response).to.have.status(200);
            return response;
        });
    });
```

I get this error (seems related to `fs.createReadStream`): 
```
Error:
write after end
    at write_ (_http_outgoing.js:635:15)
    at ClientRequest.write (_http_outgoing.js:630:10)
    at Request.write (D:\wamp64\www\***\test\***\node_modules\request\request.js:1514:27)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at FormData.emit (events.js:210:7)
    at FormData.CombinedStream.write (D:\wamp64\www\***\test\***\node_modules\combined-stream\lib\combined_stream.js:118:8)
    at DelayedStream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at DelayedStream.emit (events.js:210:7)
    at DelayedStream._handleEmit (D:\wamp64\www\***\test\***\node_modules\delayed-stream\lib\delayed_stream.js:82:15)
    at ReadStream.source.emit (D:\wamp64\www\***\test\***\node_modules\delayed-stream\lib\delayed_stream.js:29:19)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at ReadStream.Readable.push (_stream_readable.js:197:10)
    at onread (fs.js:2004:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:663:17) {stack: Error: write after end
    at write_ (_http_outgoi… FSReqWrap.wrapper [as oncomplete] (fs.js:663:17),
message: write after end}
```

Tested on Windows10 with NodeJS 6.11.0 and 8.1.3.

I found some possible solutions with Mocha (see https://stackoverflow.com/questions/10120866/how-to-unit-test-with-a-file-upload-in-mocha/19148688), but I don't know how to adapt it to Chakram.

**Comment by mikila85** [comment]
no comment until now? 👎

**Comment by harryrose** [comment]
This library hasn't been maintained for about four years, @mikila85, so I don't expect there'll be a response soon.  It looks like the readme was updated to say development had stopped in 2018 (8349da3534b350c284fa51b64581894a572d830f)
