### ISSUE TITLE
Error getting the example to work

### ISSUE THREAD

**Issue by hnasr** [dareid/chakram#123]
Hey Chakram team, new to npm stuff so forgive my ignorance if I did something wrong that suppose to be obvious. 

I have a REST API and I want to write tests in nodejs and javascript so I searched for frameworks and Chakram poped up so I wanted to start testing it. I saw some example but I can't get them to work

This is what I did. (Windows 10)

In command prompt, I created a new directory. chakram.
Then cd'ed into it and then did this

`git clone https://github.com/dareid/chakram`

`cd chakram`

`npm run pretest`

`npm run-script examples\spotify.js `

This is the error I'm getting

![image](https://user-images.githubusercontent.com/3898305/38575942-822ccbd0-3cb1-11e8-8667-3b3d7800a2ea.png)

And the log file has this
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'examples\\spotify.js' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose stack Error: missing script: examples\spotify.js
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:348:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\Hussein\chakram\chakram
6 verbose Windows_NT 10.0.14393
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "examples\\spotify.js"
8 verbose node v8.9.3
9 verbose npm  v5.5.1
10 error missing script: examples\spotify.js
11 verbose exit [ 1, true ]

```

What exactly am I missing? 

thank you!
Hussein

**Comment by hnasr** [comment]
Got it to work. This is really cool stuff...

I'm kind of confused as to why I have to name my file test.js for it to work. weird that I can't name it anything I want..  

![image](https://user-images.githubusercontent.com/3898305/38577739-a6ee1af0-3cb6-11e8-8c4b-fbbd21cd2a27.png)
