### ISSUE TITLE
Running chakram with `mocha --watch` fails tests after a few re-runs

### ISSUE THREAD

**Issue by VictorBjelkholm** [dareid/chakram#25]
I'm trying to use chakram to develop a small API. I found it useful that the tests are run with mocha so everything I did before in unit tests, can still be used with chakram. However, when running mocha with the `--watch` flag, the tests start failing after a few re-runs, for no apparent reason. If I then kill mocha and start it again, it works but only until 2-3 re-runs. After that, the tests fails.

My simple test

```
var chakram = require('chakram')
var expect = chakram.expect

function basicExpections(response) {
  expect(response).to.have.status(200)
  expect(response).to.have.header('Content-Type', 'application/json; charset=utf-8')
  expect(response).not.to.be.encoded.with.gzip
}

describe('Nodes', () => {
    it('Should be able to see empty list of nodes', () => {
      var response = chakram.get('http://localhost:3000/nodes')
      basicExpections(response)
      expect(response).to.comprise.of.json([])
      return chakram.wait()
    });
});
```

The error I receive after a few re-runs:

```
  0 passing (9ms)
  1 failing

  1) Nodes Should be able to see empty list of nodes:
     TypeError: Cannot read property 'statusCode' of undefined
      at null.<anonymous> (node_modules/chakram/lib/assertions/statuscode.js:15:44)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:304:26
      at _fulfilled (node_modules/chakram/node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/chakram/node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/chakram/node_modules/q/q.js:796:13)
      at node_modules/chakram/node_modules/q/q.js:604:44
      at runSingle (node_modules/chakram/node_modules/q/q.js:137:13)
      at flush (node_modules/chakram/node_modules/q/q.js:125:13)
```

**Comment by dareid** [comment]
Thanks for raising this issue. 
We have encountered this issue before (#10) and have not been able to discover a fix. I will hopefully have another run at it soon. I will close this issue due to duplication.
