### ISSUE TITLE
ReferenceError: "afterEach is not defined" when chakram is called outside of mocha test

### ISSUE THREAD

**Issue by dbrusnin** [dareid/chakram#55]
reference error when chakram called outside of mocha test.

Steps to reproduce:
1. Create test.js file with the next content
`var chakram = require('chakram');`
`return chakram.get("http://httpbin.org/get").then((response) => console.log(response.body));`
2. execute node command
`node test.js`

c:\dev\client\node_modules\chakram\lib\chakram.js:136
afterEach(function() {
^

ReferenceError: afterEach is not defined
    at Object.<anonymous> (c:\dev\client\node_modules\chakram\lib\chakram.js:136:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (c:\temp\dev\chkram\client.js:1:15)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)

**Comment by dareid** [comment]
Chakram relies on the mocha test framework and as such will not work without it. 
Is there any reason you are running it outside of mocha?

**Comment by dbrusnin** [comment]
I'd like to use chakram with cucumber.js.
I've found the pull request which solves this error but it wasn't merged.
https://github.com/dareid/chakram/pull/28/commits/beb85cb261b000a8a7a4e2a7e0951dcf95f38e72

**Comment by dareid** [comment]
Yes it was not merged as chakram currently relies on mocha. I will adjust this issue to request multiple supported test rummers

**Comment by BasHamer** [comment]
ran into the exact same issue, do you have any suggestions for a chakram replacement for other test runners?

**Comment by ashutoshmittal2309** [comment]
I am also looking for support for cucumber-js as it makes it easier to define tests allowing me to define Steps/Test Data from actual code. 
Let me know if there is a plan to add this feature in near future as this would really help.

**Comment by dareid** [comment]
I have not got time to add support for other test runners unfortunately. I would love to see it added to the library, I just do not have the bandwidth at the moment. 
Any contributions would be greatly received.

**Comment by acolchado** [comment]
@dareid I am getting this error and I am using mocha:

```
/Code/opentable/GCBoH-API-Test/node_modules/chakram/lib/chakram.js:161
afterEach(function() {
^

ReferenceError: afterEach is not defined
    at Object.<anonymous> (/Users/acolchado/Code/opentable/GCBoH-API-Test/node_modules/chakram/lib/chakram.js:161:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/acolchado/Code/opentable/GCBoH-API-Test/test/globals.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/acolchado/Code/opentable/GCBoH-API-Test/node_modules/mocha/bin/_mocha:345:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/acolchado/Code/opentable/GCBoH-API-Test/node_modules/mocha/bin/_mocha:344:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.
```

The following are the relevant `package.json` properties:

```
  "scripts": {
    "test": "mocha test/"
  },
  "devDependencies": {
    "chakram": "^1.5.0",
    "chakram-joi": "^1.0.0",
    "eslint": "^3.18.0",
    "eslint-config-opentable": "^6.0.0",
    "lodash": "^4.17.4",
    "mocha": "^3.2.0"
  }
```

Any ideas?

Thanks! I am new to the package and am excited to use it and contribute to it as I learn more about it.

**Comment by acolchado** [comment]
Please ignore my comment. I figure out the issue was caused due to user error. I'm in the habit of using `mocha.opts` to set a `--required ./test/globals.js` file where I set some global entries for some frameworks. This caused an issue with chakram because it assumes it's being required/imported from the spec files themselves where functions like `before`, `after`, `beforeEach`, and `afterEach` are expected to be available. In this usage, they aren't yet available.

This is what I had added to the globals.js file:

```
var chakram = require('chakram');

global.chakram = chakram;
global.expect = chakram.expect;
```

I've since made the change to import at the tests, but that will make me adjust some of my plans for my chakram usage. I was hoping to set certain things in a global file... Things like plugins, expect availability, and other useful things that would help me reduce the boiler plate of the test code.

Reducing boilerplate in this fashion is important for me because I plan to create am internal framework module that does all of the basic configuration so that repos dedicated to a group of services can inherit that configuration via a simple wrapper. Assuming afterEach will always be there makes it tough to do that.

If you're willing to explore other options for initialization, I'd be willing to contribute those changes for consideration.

Providing an option for the use of `init` function that could be used in every test's `before` hook would do the trick, but may not be the cleanest thing.

Let me know what you think @dareid.

**Comment by rohityadavrv** [comment]
Hello Daniel,
could you please tell me if you added support for cucumber.js for chakram?

**Comment by dsamburskyi** [comment]
This seems to be blocking running Chakram with Mocha programmatically, like
```mocha.addFile('./test.js').run();```
I'm getting the same ```ReferenceError: afterEach is not defined```
