### ISSUE TITLE
Handle response data before expect

### ISSUE THREAD

**Issue by albertyou2** [dareid/chakram#70]
HI @dareid 

I met a problem these days and I didn't find the solution yet . so I have to raise a issue,sorry 
The problem is that the response data from server is encrypted . So I can't 'expect()' the data directly after received a response with chakram.

Is there any method to handle data before 'expect' it?
I had tried this code as below but failed:

var postdata =  {formdata:"name=123&creater=331"}
    return chakram.post("http://192.168.10.243:10001/manage/region/addstate",undefined,postdata)
        .then(function (res) {
            // get the response success
            // decrypt res.body['data'] then set it back to res.body['data']
            res.body['data'] = decrypt( res.body['data']  )
            // expect
            expect(res.body).to.have.json("k","v");
            return chakram.wait();
        });

The error log is here: 

  Error: could not find path 'k' in object undefined
      at Object.module.exports.get (node_modules/chakram/lib/utils/objectPath.js:5:19)
      at null.<anonymous> (node_modules/chakram/lib/assertions/json.js:33:27)
      at ctx.(anonymous function) (node_modules/chakram/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chakram/node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at null.<anonymous> (node_modules/chakram/node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at ctx.(anonymous function) [as json] (node_modules/chakram/node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at tese_case_1.js:36:38
      at _fulfilled (node_modules/chakram/node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/chakram/node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/chakram/node_modules/q/q.js:796:13)
      at node_modules/chakram/node_modules/q/q.js:604:44
      at runSingle (node_modules/chakram/node_modules/q/q.js:137:13)
      at flush (node_modules/chakram/node_modules/q/q.js:125:13)

Thank you!

**Comment by dareid** [comment]
Thanks for raising the issue. Is an interesting use case.

So I think your code is almost there. I would guess at : 
```
  var postdata = {formdata:"name=123&creater=331"}
  return chakram.post("http://192.168.10.243:10001/manage/region/addstate",undefined,postdata)
  .then(function (res) {
    res.body['data'] = decrypt( res.body['data'] )
    expect(res).to.have.json("k","v");
    return chakram.wait();
  });
```

If that doesn't work give me a shout. You may also be able to wrap the chakram request methods to include the decrypting, that way your tests could be written without the decrypt step.

**Comment by albertyou2** [comment]
@dareid It works!Thanks！
